config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  get 'reviews/all' => "reviews#all"

  get 'reviews/new/:movie_id' => "reviews#new"

  get 'reviews/edit/:id' => "reviews#edit"

  put 'reviews/:id' => "reviews#update"

  delete 'reviews/:id' => "reviews#delete"

  post 'reviews/:movie_id' => "reviews#create"

  devise_for :users
  
  get 'movies/new' => "movies#new"

  get 'movies/show/:id' => "movies#show"

  get 'movies/all' => "movies#all"

  get 'movies/edit/:id' => "movies#edit"

  post 'movies' => "movies#create"

  put 'movies/:id' => "movies#update"

  delete 'movies/:id' => "movies#destroy"

  get 'movies/search' => "movies#search"

  root :to => "movies#all"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  has_attached_file :title_picture, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :title_picture, :content_type => /\Aimage\/.*\Z/

  validate :one_review_per_user

  ratyrate_rateable "user_rating"

  searchkick

  def one_review_per_user
    user_ids = []
    self.reviews.each { |review| user_ids << review.user_id }
    errors.add(:review, "a movie can only have one review per user.") unless user_ids.length == user_ids.uniq.length
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user

  validates :content, length: { in: 10..1024 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy

  ratyrate_rater

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :redirect_unless_admin, :except => [:show, :all]

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def all
    @movies = Movie.all.page(params[:page]).per(3)
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def search
    @movies = Movie.search(params[:search], page: params[:page], per_page: 1)
  end

  def create
    @movie = Movie.create(movie_params)
    if @movie.save
      redirect_to controller: :movies, action: :all
    else
      render "new"
    end
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    if @movie.save
      redirect_to controller: :movies, action: :all
    else
      render "edit"
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to controller: :movies, action: :all
  end

  private

  def movie_params
    params.require(:movie).permit!
  end

  def redirect_unless_admin
    if user_signed_in?
      redirect_to controller: :movies, action: :all unless current_user.admin? 
    else
      redirect_to controller: :movies, action: :all
    end
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def all
    @reviews = Review.where(user_id: current_user.id)
  end

  def edit
    @review = Review.find(params[:id])
    redirect_to controller: 'movies', action: 'all' unless @review.user_id == current_user.id
  end

  def create
    # TODO 3443: Do not allow more than 1 review for a movie per user
    @review = Review.create(review_params)
    @movie = Movie.find(params[:movie_id])
    @review.movie = @movie
    @review.user = current_user
    if @movie.save
      if @review.save
        redirect_to controller: :movies, action: :all
      else
        render "new"
      end
    else
      render "new"
    end
  end

  def update
    @review = Review.find(params[:id])
    redirect_to controller: 'movies', action: 'all' unless @review.user_id == current_user.id
    @review.update(review_params)
    if @review.save
      redirect_to controller: :movies, action: :all
    else
      render "edit"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to controller: :movies, action: :all
  end

  private

  def review_params
    params.require(:review).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Movie Reviews', movies_all_path, class: 'navbar-brand' %>
        </div>
        <p class="navbar-text">
          <%= link_to 'All movies', movies_all_path, class: 'navbar-link' %>
        </p>
        <% if user_signed_in? %>
          <p class="navbar-text">
            <%= link_to 'Your reviews', reviews_all_path, class: 'navbar-link' %>
          </p>
          <p class="navbar-text">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'navbar-link' %>
          </p>
          <% if current_user.admin? %>
            <p class="navbar-text">
              <%= link_to 'New movie', movies_new_path, class: 'navbar-link' %>
            </p>
          <% end %>
        <% else %>
          <p class="navbar-text">
            <%= link_to 'Sign in', new_user_session_path, class: 'navbar-link' %>
          </p>
          <p class="navbar-text">
            <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link' %>
          </p>
        <% end %>
        <%= form_tag movies_search_path, method: :get, class: 'navbar-form navbar-right' do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], class: 'form-control' %>
          </div>
          <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= f.label :title %>:
<%= f.text_field :title %><br />

<%= f.label :description %>:
<%= f.text_area :description, size: "50x10" %><br />

<%= f.label :release_date %>:
<%= f.date_field :release_date, value: "1984-05-12" %><br />

<%= f.label :rating %>:
<%= f.text_field :rating %><br />

<%= f.label :genre %>:
<%= f.text_field :genre %><br />

<%= f.label :stars %>:
<%= f.text_field :stars %><br />

<%= f.label :votes %>:
<%= f.text_field :votes %><br />

<%= f.label :title_picture %>:
<%= f.file_field :title_picture %><br />

<%= f.submit %>

app/views/movies/_movie.html.erb
<div class="col-md-4">
  <h2><%= link_to movie.title, controller: 'movies', action: 'show', id: movie.id %>
  <h2><%= link_to pluralize(movie.reviews.count, 'review'), controller: 'movies', action: 'show', id: movie.id, anchor: 'reviews' %></h2>
  <a href="<%= url_for(controller: :movies, action: :show, id: movie.id) %>"><%= image_tag movie.title_picture.url(:medium) %></a><br />
  <% if user_signed_in? %>
    <%= link_to "Write a review for #{movie.title}", controller: :reviews, action: :new, movie_id: movie.id %>
  <% end %>
</div>

app/views/movies/all.html.erb
<div class="row">
  <%= render partial: "movie", collection: @movies %>
</div>
<%= paginate @movies %>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

<%= form_for @movie, url: url_for(controller: 'movies', action: 'update'), html: { method: :put } do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

<%= form_for @movie, url: url_for(controller: 'movies', action: 'create'), html: { method: :post } do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/movies/search.html.erb
<%= render partial: "movie", collection: @movies %>
<%= paginate @movies %>

app/views/movies/show.html.erb
<h2><%= @movie.title %></h2><br /><br />
User rating: <%= rating_for @movie, "user_rating", star: 5 %><br />
<div class="row">
  <div class="col-md-5">
    <%= image_tag @movie.title_picture.url(:large) %>
  </div>
  <div class="col-md-3">
    <h4><p><%= @movie.release_date %></p></h4><br />
    <h4><p><%= @movie.rating %></p></h4><br />
    <h4><p><%= @movie.genre %></p></h4><br /><br />
    <% if user_signed_in? %>
      <%= link_to "Write a review for #{@movie.title}", controller: :reviews, action: :new, movie_id: @movie.id %>
    <% else %>
      <p><h3><%= link_to 'Sign in', new_user_session_path %></h3> to write a review</p>
    <% end %>
  </div>
  <div class="col-md-4">
    <h3><p><%= @movie.description %></p></h3><br />
  </div>
</div>

<hr>

<h2 id="reviews"><%= pluralize(@movie.reviews.count, 'reviews') %></h2><br />
<% @movie.reviews.each do |review| %>
  <p><%= review.user.email %> Wrote:</p><br />
  <p><%= review.content %></p><br />
  <p><small><%= review.created_at.to_formatted_s(:short) %></small></p><br /><br />
  <% if user_signed_in? %>
    <% if current_user.id == review.user_id %>
      <%= link_to 'Edit review', controller: :reviews, action: :edit, id: review.id %>
    <% end %>
  <% end %>
  <hr>
<% end %>

app/views/reviews/_form.html.erb
<%= f.label :content %>
<%= f.text_area :content, size: "50x10" %><br />

<%= f.submit %>

app/views/reviews/all.html.erb
<% @reviews.each do |review| %>
  <h2><%= link_to review.movie.title, controller: :movies, action: :show, id: review.movie.id %></h2><br />
  <p><%= review.content %></p><br />
  <%= link_to 'Edit review', controller: :reviews, action: :edit, id: review.id %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

<%= form_for @review, url: url_for(controller: 'reviews', action: 'update'), html: { method: :put } do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= form_for @review, url: url_for(controller: 'reviews', action: 'create'), html: { method: :post } do |f| %>
  <%= render 'form', f: f %>
<% end %>